### ISSUE TITLE
Retire docker relay?

### ISSUE THREAD

**Issue by yannh** [xelalexv/dregsy#21]
The docker relay seems to be much less efficient than the skopeo one. Syncing large registries involve downloading all tags locally first - which might take quite some space. Since the relay implementations are quite different, it makes adding new features more challenging. Is there an advantage in using the docker relay vs the Skopeo one? How about sunsetting it?

**Comment by xelalexv** [comment]
I thought I mentioned something about deprecating the Docker relay in the readme, but turns out I don't ;-) Any way to do a poll on this here?

**Comment by xelalexv** [comment]
On the other hand, we don't necessarily have to support all features in both relay types.

**Comment by xelalexv** [comment]
Due to recent refactorings, sync functionality is now much less coupled to the functionality of relays. For example, the initial implementation for #16 and #2, did not have to take particularities of either relay into account, and worked for both right away. The only burden of keeping the Docker relay that I can see at the moment is having to write more tests. I'd still say we keep it for now, and reopen this issue when the Docker relay starts hampering the progress of the project.
