### ISSUE TITLE
Support ECR public

### ISSUE THREAD

**Issue by dseynaev** [xelalexv/dregsy#60]
Any plans to support [ECR public](https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html)?

the API is seperate from the normal ECR one: https://docs.aws.amazon.com/sdk-for-go/api/service/ecrpublic/#ECRPublic.GetAuthorizationToken so while current ecr auth implementation 
won't work implementing ECR public would be very analogous

**Comment by jlbutler** [comment]
Hi @xelalexv 👋 

I have made a [comment](https://github.com/aws/containers-roadmap/issues/1262#issuecomment-1213127749) on our issue tracking tags missing from ECR Public's v2 API.

The quick ask for feedback: if we iterate toward full OCI compliance, for the dregsy use case is it OK for us to consider deferring the lexical sorting and transparent pagination token aspect of the spec, to focus on a first delivery that is the correct response body?

We're very interested in unblocking use cases like this primarily, then iterating toward full spec compliance.

If you have the time, you can reply here or on the roadmap issue? And, thanks for your time!

**Comment by xelalexv** [comment]
Hi @jlbutler, thanks for contacting me! For dregsy, getting the tags unsorted in the reply isn't an issue. We usually have to get all tags and perform various kinds of filtering on the received set. So as long as we can get the complete set, your intermediate implementation would already unblock this issue here. Pagination would be of interest for very large tag sets, but that's rather an edge case and can wait until later. So, your suggested path to full OCI compliance would help us already from the start!

**Comment by jlbutler** [comment]
> Hi @jlbutler, thanks for contacting me! For dregsy, getting the tags unsorted in the reply isn't an issue. We usually have to get all tags and perform various kinds of filtering on the received set. So as long as we can get the complete set, your intermediate implementation would already unblock this issue here. Pagination would be of interest for very large tag sets, but that's rather an edge case and can wait until later. So, your suggested path to full OCI compliance would help us already from the start!

Thanks so much, your guidance is very appreciated!

**Comment by xelalexv** [comment]
Just tried tout the implementation I did last year, and it seems to be working without problems now. I'll merge this soon.

**Comment by xelalexv** [comment]
implemented with #94, will be included in next release
